import random

sentences = [
    "As you consider all the possible ways to improve yourself and the world, you notice John Travolta seems fairly unhappy.",
    "The sunblock was handed to the girl before practice, but the burned skin was proof she did not apply it.",
    "The swirled lollipop had issues with the pop rock candy.",
    "He found his art never progressed when he literally used his sweat and tears.",
    "I used to live in my neighbor's fishpond, but the aesthetic wasn't to my taste.",
    "The most exciting eureka moment I've had was when I realized that the instructions on food packets were just guidelines.",
    "They throw cabbage that turns your brain into emotional baggage.",
    "Kevin embraced his ability to be at the wrong place at the wrong time.",
    "She only paints with bold colors; she does not like pastels.",
    "The view from the lighthouse excited even the most seasoned traveler.",
    "Random words in front of other random words create a random sentence.",
    "He knew it was going to be a bad day when he saw mountain lions roaming the streets.",
    "Plans for this weekend include turning wine into water.",
    "At that moment I was the most fearsome weasel in the entire swamp.",
    "We have young kids who often walk into our room at night for various reasons including clowns in the closet.",
    "He decided to count all the sand on the beach as a hobby.",
    "She saw no irony asking me to change but wanting me to accept her for who she is.",
    "The tortoise jumped into the lake with dreams of becoming a sea turtle.",
    "That must be the tenth time I've been arrested for selling deep-fried cigars.",
    "Peanuts don't grow on trees, but cashews do.",
    "She let the balloon float up into the air with her hopes and dreams.",
    "He turned in the research paper on Friday; otherwise, he would have not passed the class.",
    "Pantyhose and heels are an interesting choice of attire for the beach.",
    "There are over 500 starfish in the bathroom drawer.",
    "He went on a whiskey diet and immediately lost three days.",
    "He kept telling himself that one day it would all somehow make sense.",
    "When money was tight, he'd get his lunch money from the local wishing well.",
    "One small action would change her life, but whether it would be for better or for worse was yet to be determined.",
    "The glacier came alive as the climbers hiked closer.",
    "At that moment she realized she had a sixth sense.",
    "She borrowed the book from him many years ago and hasn't yet returned it.",
    "That is an appealing treasure map that I can't read.",
    "The trick to getting kids to eat anything is to put catchup on it.",
    "The wooden spoon couldn’t cut but left emotional scars.",
    "Dolores wouldn't have eaten the meal if she had known what it actually was.",
    "At last",
    "You'll see the rainbow bridge after it rains cats and dogs.",
    "The elephant didn't want to talk about the person in the room.",
    "The elderly neighborhood became enraged over the coyotes who had been blamed for the poodle’s disappearance.",
    "The lyrics of the song sounded like fingernails on a chalkboard.",
    "Her daily goal was to improve on yesterday.",
    "Green should have smelled more tranquil, but somehow it just tasted rotten.",
    "The water flowing down the river didn’t look that powerful from the car",
    "As he entered the church he could hear the soft voice of someone whispering into a cell phone.",
    "He was an introvert that extroverts seemed to love.",
    "He was surprised that his immense laziness was inspirational to others.",
    "Siri became confused when we reused to follow her directions.",
    "He had unknowingly taken up sleepwalking as a nighttime hobby.",
    "Watching the geriatric men’s softball team brought back memories of 3 yr olds playing t-ball.",
    "They say people remember important moments in their life well, yet no one even remembers their own birth.",
    "Writing a list of random sentences is harder than I initially thought it would be.",
    "He had accidentally hacked into his company's server.",
    "You bite up because of your lower jaw.",
    "As he entered the church he could hear the soft voice of someone whispering into a cell phone.",
    "We have never been to Asia, nor have we visited Africa.",
    "The golden retriever loved the fireworks each Fourth of July.",
    "When he asked her favorite number, she answered without hesitation that it was diamonds.",
    "Please put on these earmuffs because I can't you hear.",
    "Written warnings in instruction manuals are worthless since rabbits can't read.",
    "Iron pyrite is the most foolish of all minerals.",
    "She was too short to see over the fence.",
    "She was only made the society president because she can whistle with her toes.",
    "The waitress was not amused when he ordered green eggs and ham.",
    "He found a leprechaun in his walnut shell.",
    "Be careful with that butter knife.",
    "Being unacquainted with the chief raccoon was harming his prospects for promotion.",
    "I’m working on a sweet potato farm.",
    "My uncle's favorite pastime was building cars out of noodles.",
    "I am never at home on Sundays.",
    "It dawned on her that others could make her happier, but only she could make herself happy.",
    "The changing of down comforters to cotton bedspreads always meant the squirrels had returned.",
    "The father died during childbirth.",
    "She had convinced her kids that any mushroom found on the ground would kill them if they touched it.",
    "I used to practice weaving with spaghetti three hours a day but stopped because I didn't want to die alone.",
    "Nothing is as cautiously cuddly as a pet porcupine.",
    "The hawk didn’t understand why the ground squirrels didn’t want to be his friend.",
    "Sixty-Four comes asking for bread.",
    "Truth in advertising and dinosaurs with skateboards have much in common.",
    "He is no James Bond; his name is Roger Moore.",
    "Tomorrow will bring something new, so leave today as a memory.",
    "Hit me with your pet shark!",
    "The clock within this blog and the clock on my laptop are 1 hour different from each other.",
    "They desperately needed another drummer since the current one only knew how to play bongos.",
    "He was sure the Devil created red sparkly glitter.",
    "My biggest joy is roasting almonds while stalking prey.",
    "The Guinea fowl flies through the air with all the grace of a turtle.",
    "It was a really good Monday for being a Saturday.",
    "Warm beer on a cold day isn't my idea of fun.",
    "Best friends are like old tomatoes and shoelaces.",
    "She was disgusted he couldn’t tell the difference between lemonade and limeade.",
    "The ants enjoyed the barbecue more than the family.",
    "When motorists sped in and out of traffic, all she could think of was those in need of a transplant.",
    "She used her own hair in the soup to give it more flavor.",
    "In that instant, everything changed.",
    "I became paranoid that the school of jellyfish was spying on me.",
    "I received a heavy fine but it failed to crush my spirit.",
    "I'm confused: when people ask me what's up, and I point, they groan.",
    "It's difficult to understand the lengths he'd go to remain short.",
    "He created a pig burger out of beef.",
    "As time wore on, simple dog commands turned into full paragraphs explaining why the dog couldn’t do something.",
    "They finished building the road they knew no one would ever use.",
    "Everyone was curious about the large white blimp that appeared overnight.",
    "A purple pig and a green donkey flew a kite in the middle of the night and ended up sunburnt.",
    "He decided that the time had come to be stronger than any of the excuses he'd used until then.",
    "The overpass went under the highway and into a secret world.",
    "There are over 500 starfish in the bathroom drawer.",
    "Always bring cinnamon buns on a deep-sea diving expedition.",
    "As she walked along the street and looked in the gutter, she realized facemasks had become the new cigarette butts.",
    "Their argument could be heard across the parking lot.",
    "Flying fish flew by the space station.",
    "You're good at English when you know the difference between a man eating chicken and a man-eating chicken.",
    "She had the gift of being able to paint songs.",
    "She wanted a pet platypus but ended up getting a duck and a ferret instead.",
    "There aren't enough towels in the world to stop the sewage flowing from his mouth.",
    "A quiet house is nice until you are ordered to stay in it for months.",
    "Nothing is as cautiously cuddly as a pet porcupine.",
    "Purple is the best city in the forest.",
    "The underground bunker was filled with chips and candy.",
    "Everything was going so well until I was accosted by a purple giraffe.",
    "The two walked down the slot canyon oblivious to the sound of thunder in the distance.",
    "Patricia found the meaning of life in a bowl of Cheerios.",
    "He decided to live his life by the big beats manifesto.",
    "You have no right to call yourself creative until you look at a trowel and think that it would make a great lockpick.",
    "Mom didn’t understand why no one else wanted a hot tub full of jello.",
    "He used to get confused between soldiers and shoulders, but as a military man, he now soldiers responsibility.",
    "It didn't make sense unless you had the power to eat colors.",
    "I’m working on a sweet potato farm.",
    "I was very proud of my nickname throughout high school but today- I couldn’t be any different to what my nickname was.",
    "Pair your designer cowboy hat with scuba gear for a memorable occasion.",
    "Sometimes it is better to just walk away from things and go back to them later when you’re in a better frame of mind.",
    "Various sea birds are elegant, but nothing is as elegant as a gliding pelican.",
    "The changing of down comforters to cotton bedspreads always meant the squirrels had returned.",
    "She had a habit of taking showers in lemonade.",
    "While on the first date he accidentally hit his head on the beam.",
    "Dolores wouldn't have eaten the meal if she had known what it actually was.",
    "The stranger officiates the meal.",
    "Baby wipes are made of chocolate stardust.",
    "When confronted with a rotary dial phone the teenager was perplexed.",
    "Facing his greatest fear, he ate his first marshmallow.",
    "I checked to make sure that he was still alive.",
    "Douglas figured the best way to succeed was to do the opposite of what he'd been doing all his life.",
    "The bullet pierced the window shattering it before missing Danny's head by mere millimeters.",
    "The snow-covered path was no help in finding his way out of the back-country.",
    "He was willing to find the depths of the rabbit hole in order to be with her.",
    "He colored deep space a soft yellow.",
    "He had a hidden stash underneath the floorboards in the back room of the house.",
    "The beach was crowded with snow leopards.",
    "She lived on Monkey Jungle Road and that seemed to explain all of her strangeness.",
    "Courage and stupidity were all he had.",
    "He turned in the research paper on Friday; otherwise, he would have not passed the class.",
]


def generate_random_paragraph(n=700):
    paragraph = ""
    total_words = 0
    while total_words < n:
        s = random.choice(sentences)
        w = len(s.split(" "))
        paragraph += s + " "
        total_words += w
    return paragraph
